---
env:
  browser: true
  node: true
  es2020: true
  jest/globals: true
parser: '@typescript-eslint/parser'
# parserOptions:
  # project: ./tsconfig.json
  # ecmaFeatures:
  #     jsx: true
plugins:
  - jest
  # - react
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - prettier
  - prettier/@typescript-eslint
rules:
  '@typescript-eslint/explicit-function-return-type': off
  # '@typescript-eslint/explicit-module-boundary-types': off
  'no-magic-numbers': 0
  '@typescript-eslint/no-magic-numbers': 1

